/*
 * This file is part of MCServerAdmin.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2014 Sergio M. Afonso Fumero <theSkatrak@gmail.com>
 */

#ifndef SUPERFLATSETTINGS_H
#define SUPERFLATSETTINGS_H

#include <QList>
#include <QPair>
#include <QString>

enum BlockType: short;
enum BiomeID: short;

class SuperflatSettings {
public:
  explicit SuperflatSettings(QString text = "");
  SuperflatSettings(const SuperflatSettings& other);

  bool setStringRepresentation(QString text);
  QString getStringRepresentation() const;

  void addTopLayer(BlockType element, int height);
  void addLayer(int position, BlockType element, int height);
  void addBottomLayer(BlockType element, int height);

  void setLayerElement(int layer, BlockType element);
  void setLayerSize(int layer, int size);

  QPair<BlockType, int> getLayerInfo(int layer) const;
  BlockType getLayerElement(int layer) const;
  int getLayerHeight(int layer) const;
  int getLayerCount() const;

  QList< QPair<BlockType, int> > getLayers() const;

private:
  QList< QPair<BlockType, int> > layers;
  BiomeID biome; // TODO set and get biome
  // TODO Structure generation options
};

enum BlockType: short {
  INVALIDBLOCKTYPE = -1,
  AIR,
  STONE,
  GRASSBLOCK,
  DIRT,
  COBBLESTONE,
  WOODPLANKS,
  SAPLING,
  BEDROCK,
  WATER,
  STATIONARYWATER,
  LAVA,
  STATIONARYLAVA,
  SAND,
  GRAVEL,
  GOLDORE,
  IRONORE,
  COALORE,
  WOOD,
  LEAVES,
  SPONGE,
  GLASS,
  LAPISLAZULIORE,
  LAPISLAZULIBLOCK,
  DISPENSER,
  SANDSTONE,
  NOTEBLOCK,
  BED,
  POWEREDRAIL,
  DETECTORRAIL,
  STICKYPISTON,
  COBWEB,
  GRASS,
  DEADBUSH,
  PISTON,
  PISTONEXTENSION,
  WOOL,
  BLOCKMOVEDBYPISTON,
  DANDELION,
  POPPY,
  BROWNMUSHROOM,
  REDMUSHROOM,
  BLOCKOFGOLD,
  BLOCKOFIRON,
  DOUBLESTONESLAB,
  STONESLAB,
  BRICKS,
  TNT,
  BOOKSHELF,
  MOSSSTONE,
  OBSIDIAN,
  TORCH,
  FIRE,
  MONSTERSPAWNER,
  OAKWOODSTAIRS,
  CHEST,
  REDSTONEWIRE,
  DIAMONDORE,
  BLOCKOFDIAMOND,
  CRAFTINGTABLE,
  WHEAT,
  FARMLAND,
  FURNACE,
  BURNINGFURNACE,
  STANDINGSIGN,
  OAKDOOR,
  LADDER,
  RAIL,
  COBBLESTONESTAIRS,
  WALLSIGN,
  LEVER,
  STONEPRESSUREPLATE,
  IRONDOOR,
  WOODENPRESSUREPLATE,
  REDSTONEORE,
  GLOWINGREDSTONEORE,
  REDSTONETORCHINACTIVE,
  REDSTONETORCHACTIVE,
  STONEBUTTON,
  SNOWLAYER,
  ICE,
  SNOW,
  CACTUS,
  CLAY,
  SUGARCANE,
  JUKEBOX,
  FENCE,
  PUMPKIN,
  NETHERRACK,
  SOULSAND,
  GLOWSTONE,
  NETHERPORTAL,
  JACKOLANTERN,
  CAKE,
  REDSTONEREPEATERINACTIVE,
  REDSTONEREPEATERACTIVE,
  STAINEDGLASS,
  TRAPDOOR,
  MONSTEREGG,
  STONEBRICKS,
  HUGEBROWNMUSHROOM,
  HUGEREDMUSHROOM,
  IRONBARS,
  GLASSPANE,
  MELON,
  PUMPKINSTEM,
  MELONSTEM,
  VINES,
  FENCEGATE,
  BRICKSTAIRS,
  STONEBRICKSTAIRS,
  MYCELIUM,
  LILYPAD,
  NETHERBRICK,
  NETHERBRICKFENCE,
  NETHERBRICKSTAIRS,
  NETHERWART,
  ENCHANTMENTTABLE,
  BREWINGSTAND,
  CAULDRON,
  ENDPORTAL,
  ENDPORTALBLOCK,
  ENDSTONE,
  DRAGONEGG,
  REDSTONELAMPINACTIVE,
  REDSTONELAMPACTIVE,
  DOUBLEWOODENSLAB,
  WOODENSLAB,
  COCOA,
  SANDSTONESTAIRS,
  EMERALDORE,
  ENDERCHEST,
  TRIPWIREHOOK,
  TRIPWIRE,
  BLOCKOFEMERALD,
  SPRUCEWOODSTAIRS,
  BIRCHWOODSTAIRS,
  JUNGLEWOODSTAIRS,
  COMMANDBLOCK,
  BEACON,
  COBBLESTONEWALL,
  FLOWERPOT,
  CARROT,
  POTATO,
  WOODENBUTTON,
  MOBHEAD,
  ANVIL,
  TRAPPEDCHEST,
  LIGHTWEIGHTEDPRESSUREPLATE,
  HEAVYWEIGHTEDPRESSUREPLATE,
  UNPOWEREDCOMPARATOR,
  POWEREDCOMPARATOR,
  DAYLIGHTSENSOR,
  BLOCKOFREDSTONE,
  NETHERQUARTZORE,
  HOPPER,
  BLOCKOFQUARTZ,
  QUARTZSTAIRS,
  ACTIVATORRAIL,
  DROPPER,
  STAINEDCLAY,
  STAINEDGLASSPANE,
  ACACIALEAVES,
  ACACIAWOOD,
  ACACIAWOODSTAIRS,
  DARKOAKWOODSTAIRS,
  SLIMEBLOCK,
  BARRIER,
  IRONTRAPDOOR,
  PRISMARINE,
  SEALANTERN,
  HAYBLOCK,
  CARPET,
  HARDENEDCLAY,
  BLOCKOFCOAL,
  PACKEDICE,
  LARGEFLOWERS,
  STANDINGBANNER,
  WALLBANNER,
  INVERTEDDAYLIGHTSENSOR,
  REDSANDSTONE,
  REDSANDSTONESTAIRS,
  DOUBLEREDSANDSTONESLAB,
  REDSANDSTONESLAB,
  SPRUCEFENCEGATE,
  BIRCHFENCEGATE,
  JUNGLEFENCEGATE,
  DARKOAKFENCEGATE,
  ACACIAFENCEGATE,
  SPRUCEFENCE,
  BIRCHFENCE,
  JUNGLEFENCE,
  DARKOAKFENCE,
  ACACIAFENCE,
  SPRUCEDOOR,
  BIRCHDOOR,
  JUNGLEDOOR,
  ACACIADOOR,
  DARKOAKDOOR
};

enum BiomeID: short {
  INVALIDBIOME = -1,
  OCEAN,
  PLAINS,
  DESERT,
  EXTREMEHILLS,
  FOREST,
  TAIGA,
  SWAMPLAND,
  RIVER,
  NETHER,
  END,
  FROZENOCEAN,
  FROZENRIVER,
  ICEPLAINS,
  ICEMOUNTAINS,
  MUSHROOMISLAND,
  MUSHROOMISLANDSHORE,
  BEACH,
  DESERTHILLS,
  FORESTHILLS,
  TAIGAHILLS,
  EXTREMEHILLSEDGE,
  JUNGLE,
  JUNGLEHILLS,
  JUNGLEEDGE,
  DEEPOCEAN,
  STONEBEACH,
  COLDBEACH,
  BIRCHFOREST,
  BIRCHFORESTHILLS,
  ROOFEDFOREST,
  COLDTAIGA,
  COLDTAIGAHILLS,
  MEGATAIGA,
  MEGATAIGAHILLS,
  EXTREMEHILLSPLUS,
  SAVANNA,
  SAVANNAPLATEAU,
  MESA,
  MESAPLATEAUF,
  MESAPLATEAU,
  SUNFLOWERPLAINS,
  DESERTM,
  EXTREMEHILLSM,
  FLOWERFOREST,
  TAIGAM,
  SWAMPLANDM,
  ICEPLAINSSPIKES,
  JUNGLEM,
  JUNGLEEDGEM,
  BIRCHFORESTM,
  BIRCHFORESTHILLSM,
  ROOFEDFORESTM,
  COLDTAIGAM,
  MEGASPRUCETAIGA,
  MEGASPRUCETAIGAHILLS,
  EXTREMEHILLSPLUSM,
  SAVANNAM,
  SAVANNAPLATEAUM,
  MESABRYCE,
  MESAPLATEAUFM,
  MESAPLATEAUM
};

#endif // SUPERFLATSETTINGS_H
